pub const RESERVED_FLAG_SHIFT: u64 = 1;
pub const INTERRUPT_FLAG_SHIFT: u64 = 9;

pub const RESERVED_FLAG: u64 = 1 << RESERVED_FLAG_SHIFT;
pub const INTERRUPT_FLAG: u64 = 1 << INTERRUPT_FLAG_SHIFT;

pub const DEFAULT_FLAGS: u64 = RESERVED_FLAG | INTERRUPT_FLAG;
